### ISSUE TITLE
Issue running code

### ISSUE THREAD

**Issue by Ghulam111** [vqdang/hover_net#12] opened 2019-09-27 04:01 UTC
hey can you please explain how can we run this code on our ConSep dataset once we have dataset downloaded.im facing various problems running this project related to assigning directories.

**Comment by vqdang** [comment] 2019-09-27 04:25
Hi,

For a start, use https://github.com/vqdang/hover_net/blob/master/src/extract_patches.py to generate your training and validation patches, please read the comment within the code for details on the option as well as what should be changed.

After that, you should modify the `config.py` accordingly, we have already had sample paths there, and also please read the `config.py` code and its comment too.

For any additional problems, please provide more details about your problem because we could not answer given this limited amount of info otherwise. Such as why/where/how this variable etc.

**Comment by Ghulam111** [comment] 2019-09-27 04:33
thanks for getting back , ill update you shortly

**Comment by Ghulam111** [comment] 2019-09-27 05:30
- what changes have to be made here, 


`self.train_dir = ['../../../train/Kumar_old_GT/%s/train/XXXX/'      % data_code_dict[self.model_type]]
        self.valid_dir = ['../../../train/Kumar_old_GT/%s/valid_same/XXXX/' % data_code_dict[self.model_type], 
                          '../../../train/Kumar_old_GT/%s/valid_diff/XXXX/' % data_code_dict[self.model_type]]`

- do we have to give path of downloaded pretrained weights in opt/hover.py

- are these changes correct 
`img_ext = '.png'
    data_mode = 'train'
    img_dir = 'C:\Users\Ghulam\CoNSeP\Train\Images' 
    ann_dir = 'C:\Users\Ghulam\CoNSeP\Train\Labels'`
`out_root_path = "C:\Users\Ghulam\train\UHCW\%dx%d_%dx%d" % \
                        (win_size[0], win_size[1], step_size[0], step_size[1])
    out_dir = "%s\%s\%s" % (out_root_path, data_mode, 'XXXX\')
`

**Comment by vqdang** [comment] 2019-09-27 07:36
- `self.train_dir` is a list of directories where each contains training patches generated by `extract_patches.py`. `self.valid_dir` is the same but for validation patches.

- If you want to reproduce the paper then we recommend you to use it, please check https://github.com/vqdang/hover_net/blob/master/src/opt/hover.py to know where you should provide the pre-trained weight path.

- Please ensure the directories paths are ended with a slash such as `'C:/Users/Ghulam/CoNSeP/Train/Labels/' and I advise you to switch `\` to `/`. 

- To double check whether your data or input were generated correctly, you can run `python train.py --view train` to check the dataloader output for the data from `self.train_dir`

**Comment by Ghulam111** [comment] 2019-09-27 07:41
alright thanks for help, ill do accordingly and update

**Comment by Ghulam111** [comment] 2019-09-27 08:26
C:\Users\Ghulam\hover_net-master\src>python extract_patches.py
train_1.png
Traceback (most recent call last):
  File "extract_patches.py", line 74, in <module>
    img = np.concatenate([img, ann], axis=-1)

im facing this error while running extract_patches.py

**Comment by Ghulam111** [comment] 2019-09-27 08:32
also im facing this error when running 

C:\Users\Ghulam\hover_net-master\src>python train.py --gpu="gpu_ids"
[0927 08:29:29 @sessinit.py:294] Loading dictionary from C:\Users\Ghulam\ImageNet-ResNet50-Preact.npz ...
[270, 270] [80, 80]
Traceback (most recent call last):
  File "train.py", line 268, in <module>
    trainer.run()
  File "train.py", line 236, in run
    self.run_once(opt, sess_init=init_weights, save_dir=log_dir)
  File "train.py", line 170, in run_once
    train_datagen = self.get_datagen(opt['train_batch_size'], mode='train')
  File "train.py", line 158, in get_datagen
    nr_procs=nr_procs)
  File "C:\Users\Ghulam\hover_net-master\src\loader\loader.py", line 72, in train_generator
    ds = BatchDataByShape(ds, batch_size, idx=0)
  File "C:\Anaconda\lib\site-packages\tensorpack\dataflow\common.py", line 210, in __init__
    super(BatchDataByShape, self).__init__(ds, batch_size, remainder=False)
  File "C:\Anaconda\lib\site-packages\tensorpack\dataflow\common.py", line 96, in __init__
    assert batch_size <= len(ds)
AssertionError

**Comment by simongraham** [comment] 2019-09-27 08:53
First of all let's deal with the first error. This means that the dimensions are not the same when concatenating the image and the label. This relates specifically to the final (3rd) dimension. Please print the image and label and this will be verified. When working with the CoNSeP dataset, the labels should be of shape WxHx2. Are you extracting patches from the original labels or are you separating the channels before extracting?

For your second error, this will be because the paths to the train and validation datasets are not quite right.

**Comment by Ghulam111** [comment] 2019-09-27 09:28
C:\Users\Ghulam\hover_net-master\src>python extract_patches.py
train_1.png
(1000, 1000, 2, 1)
(1000, 1000, 3)
Traceback (most recent call last):
  File "extract_patches.py", line 76, in <module>
    img = np.concatenate([img, ann], axis=-1)
ValueError: all the input arrays must have same number of dimensions

first one is print(ann.shape)
        2nd is print(img.shape)

**Comment by simongraham** [comment] 2019-09-27 10:09
It seems that np.expand_dims is getting called, which happens when `type_classification = False` in `config.py`. Please can you make sure that `type_classification = True`. Let us know if this is the problem.

**Comment by Ghulam111** [comment] 2019-09-27 10:14
C:\Users\Ghulam\hover_net-master\src>python extract_patches.py
train_1.png
Traceback (most recent call last):
  File "extract_patches.py", line 56, in <module>
    ann_inst = ann[...,0]
NameError: name 'ann' is not defined

**Comment by simongraham** [comment] 2019-09-27 10:36
Please pull the latest change from the `extract_patches.py` script. That will remove the above error

**Comment by Ghulam111** [comment] 2019-09-27 10:49
- i haven't made any change in extract_patches.py i just changed type_classification  =  True in config.py , except these.

` ```
step_size = [540, 540] # should match self.train_mask_shape (config.py) 
    win_size  = [80, 80] # should be at least twice time larger than 
                           # self.train_base_shape (config.py) to reduce 
                           # the padding effect during augmentation
```

    xtractor = PatchExtractor(win_size, step_size)

    ###
    img_ext = '.png'
    data_mode = 'train'
    img_dir = 'C:/Users/Ghulam/CoNSeP/Train/Images/' 
    ann_dir = 'C:/Users/Ghulam/CoNSeP/Train/Labels/' 
    ####
    out_root_path = "C:/Users/Ghulam/Train/UHCWL/%dx%d_%dx%d" % \
                        (win_size[0], win_size[1], step_size[0], step_size[1])
    out_dir = "%s/%s/%s/" % (out_root_path, data_mode, 'XXXX')

- i'm running extract_patch file separately by running from command prompt.

**Comment by simongraham** [comment] 2019-09-27 10:55
Yes, this is fine using `python extract_patches.py` is the correct way to do this. Above, I mentioned that you should pull the latest changes of `extract_patches.py`. I added a line of code at line 57 that will fix the bug. After doing this please run again and let us know if this fixes your issue.

**Comment by Ghulam111** [comment] 2019-09-27 11:10
thanks that error is gone , but the dimension mismatch error is still there in line 78, 
ann has shape ((1000, 2000)
img has shape((1000, 1000, 3)

**Comment by simongraham** [comment] 2019-09-27 11:49
Okay, there was a problem with the concatenation axis. I have instead modified the corresponding line:

https://github.com/vqdang/hover_net/blob/master/src/extract_patches.py#L66

Here, instead we now use `np.dstack()` instead of `np.concatenate()`

Again, please update us :D

**Comment by Ghulam111** [comment] 2019-09-27 12:20
C:\Users\Ghulam\hover_net-master\src>python extract_patches.py
train_1.png
(1000, 1000, 2)
(1000, 1000, 3)
train_10.png
Traceback (most recent call last):
  File "extract_patches.py", line 69, in <module>
    assert np.max(ann[...,1]) <= 4, np.max(ann[...,1])
AssertionError: 7

but if i comment out this line, code runs

**Comment by simongraham** [comment] 2019-09-27 12:47
Yes, this was just an assertion and so would run if commented out like you did. We have now fixed the assertion at line 64:

https://github.com/vqdang/hover_net/blob/master/src/extract_patches.py#L64

Thanks for spotting this. The code will now run smoothly. Let us know if you have any more questions.

**Comment by Ghulam111** [comment] 2019-09-27 13:05
👍 ok the code is running fine, but im facing problems with train.py . can u please walk me through the edits there, 

- i have given paths to pathches directories
`self.data_ext = '.npy' 
        # list of directories containing validation patches
        self.train_dir = ['C:/Users/Ghulam/train/UHCW/504x504_252x252/train/XXXX']
        self.valid_dir = ['C:/Users/Ghulam/train/valid']`

- i have given path of pre-trained weights npz file in opt/hover.py

**Comment by vqdang** [comment] 2019-09-27 13:10
@Ghulam111  Please attach the stack trace, I could only guess but I think you haven't made validation data according to this `self.valid_dir = ['C:/Users/Ghulam/train/valid']`

**Comment by Ghulam111** [comment] 2019-09-27 13:14
![Untitled](https://user-images.githubusercontent.com/55826990/65771896-b568da80-e128-11e9-978c-18b63ba43179.png)

**Comment by vqdang** [comment] 2019-09-27 13:21
@Ghulam111 Sorry, I know why now, should have looked at more carefully, please update with this
```
self.train_dir = ['C:/Users/Ghulam/train/UHCW/504x504_252x252/train/XXXX/'] 
self.valid_dir = ['C:/Users/Ghulam/train/valid/']
```
So, any directory path used in our code should be ended with `/` explicitly. 

Additionally, your run command is wrong, should be, for example, `python train.py --gpu="0"` with `0` denote GPU 0 if you have multiple GPUs.

**Comment by simongraham** [comment] 2019-09-27 13:22
First, when running the script, the <gpu_ids> needs to be substituted with the actual GPU ids. For instance, if you are running on a single GPU, you may use python train.py —gpu=‘0’ 

The error you are getting is normally because of incorrect paths to your training and validation patches. After you have fixed the above, re run the code and see if you get the same error

**Comment by vqdang** [comment] 2019-09-27 13:30
Forgot to add, because it seems you are attempting to run on Windows, please refer to this #8

**Comment by Ghulam111** [comment] 2019-09-27 13:37
![Untitled](https://user-images.githubusercontent.com/55826990/65773438-d67efa80-e12b-11e9-8d53-27f7b939108a.png)

`self.data_ext = '.npy' 
        # list of directories containing validation patches
        self.train_dir = ['C/Users/Ghulam/Train/UHCWL/80x80_540x540/train/XXXX/']
        self.valid_dir = ['C:/Users/Ghulam/Valid/UHCWL/80x80_540x540/train/XXXX/']`

**Comment by Ghulam111** [comment] 2019-09-27 13:38
im running azure virtual windows 10 instance with tesla k80 gpu

**Comment by vqdang** [comment] 2019-09-27 14:02
I suggest you to double check your input path again.
>C/Users/Ghulam/Train/UHCWL/80x80_540x540/train/XXXX/
>C:/Users/Ghulam/Train/UHCWL/80x80_540x540/train/XXXX/

**Comment by Ghulam111** [comment] 2019-09-27 14:05
C:\Users\Ghulam\Valid\UHCWL\80x80_540x540\train\XXXX\

C:\Users\Ghulam\Train\UHCWL\80x80_540x540\train\XXXX\

 i have checked , these are the directories where .npy files are created

**Comment by Ghulam111** [comment] 2019-09-27 14:08
in the `extract_patch.py` file  using `extract_type = 'mirror'`  gives this error `ValueError: index can't contain negative values` , but using e`xtract_type = 'valid'` runs fine.

**Comment by simongraham** [comment] 2019-09-27 14:15
I think you may be extracting with win_size and step_size the wrong way round. Please use win_size = 540 and step_size = 80

**Comment by Ghulam111** [comment] 2019-09-27 14:17
ok i will do , what should be extract_type at line 17

**Comment by Ghulam111** [comment] 2019-09-27 14:20
the code is running for extract_patch, i will let you know

**Comment by vqdang** [comment] 2019-09-27 14:25
https://github.com/vqdang/hover_net/blob/839bc2daadc265cba3c2d27e9bb7fbbb0e9ee247/src/extract_patches.py#L22-L30

Current option is for mirconet, so you have to set `step_size=[80, 80]` and `win_size=[540, 540]` and `extract_type = 'valid'`

Anyways, please always attach stack trace no matter what, it will make it easier for all of us. You can wrap the the logging output between ``` to format it.

**Comment by Ghulam111** [comment] 2019-09-27 14:31
a folder of size 27 GB is created.

**Comment by Ghulam111** [comment] 2019-09-27 14:35
do i have to run `extract_patch.py` again for validation data. can i comment out `self.valid_dir`

**Comment by vqdang** [comment] 2019-09-27 14:37
For debugging purpose, you can set `self.valid_dir` point to same dir as training but it would be unwise to run actual training without validation data.

**Comment by Ghulam111** [comment] 2019-09-27 14:39
yes , i think code is executing now , only problem left is of the gpu
![Untitled](https://user-images.githubusercontent.com/55826990/65778011-9e2fea00-e134-11e9-8281-a3c53af204f7.png)

**Comment by Ghulam111** [comment] 2019-09-27 14:42
do i have to install all gpu drivers like CUDA etc.

**Comment by simongraham** [comment] 2019-09-27 14:43
As we have mentioned in the above thread, please give the actual GPU ID. For instance, if you have a single GPU system and you are running with 1 GPU, use:

`python train.py --gpu='0'`

if you are using 2 GPUs, use:

`python train.py --gpu='0,1'`

**Comment by Ghulam111** [comment] 2019-09-27 14:47
![Untitled](https://user-images.githubusercontent.com/55826990/65778591-ba805680-e135-11e9-8012-975e4db09886.png)

**Comment by vqdang** [comment] 2019-09-27 14:50
For the record, which version of tensorpack and tensorflow are you using? The above errors often happen due to the change in the library naming convention. Please check https://github.com/vqdang/hover_net/blob/master/requirements.txt and #9

**Comment by Ghulam111** [comment] 2019-09-27 14:53
should i run install requirements.txt

**Comment by simongraham** [comment] 2019-09-27 14:55
It is important to create a new environment and install the specific libraries with the given version that we have provided in `requirements.txt`

**Comment by Ghulam111** [comment] 2019-09-27 14:57
alright ,will do and update you

**Comment by Ghulam111** [comment] 2019-09-27 15:02
can u please provide commands for creating new environment in windows

**Comment by Ghulam111** [comment] 2019-09-27 15:11
what is the command to run requirments.txt

**Comment by Ghulam111** [comment] 2019-09-27 15:18
can you please provide windows equivalent command for this
`pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.12.0-cp36-cp36m-linux_x86_64.whl`

**Comment by Ghulam111** [comment] 2019-09-27 15:25
looks like i have successfully compiled and training is started, thanks for helping me.

**Comment by simongraham** [comment] 2019-09-27 15:45
Great job. I’m glad we could be of assistance. We will now close this issue.

**Closed by simongraham** 2019-09-27 15:45 UTC
Labels: usage

**Comment by siddharthamantrala** [comment] 2019-10-10 04:52
I am facing the error of FilenotfoundError for the stats.json file while running the infer.py file. Do I need to train the model to generate the stats.json file?

Thanks,
Sid

**Comment by vqdang** [comment] 2019-10-10 05:30
@siddharthamantrala, Please check this answer
https://github.com/vqdang/hover_net/issues/13#issuecomment-538229913

If you just want to run the inference, please use the uploaded weight and read the above to know how to run a custom checkpoint path.

**Comment by siddharthamantrala** [comment] 2019-10-10 06:44
@vqdang  Could I know where the wieghts have been uploaded, am not able to find it through any link in the repo?

Thanks,
Sid

**Comment by vqdang** [comment] 2019-10-10 07:29
Clearly, it seems you didn't read the info put on the page at all because it is right there on https://github.com/vqdang/hover_net/tree/master/src#inference

**Comment by siddharthamantrala** [comment] 2019-10-11 06:50
I have given the model_path as the path to the .npz checkpoint file and gave the other corresponding paths to the consep test dataset with the .png extension. and tried executing infer., I got the the error message saying NotImplementedError. Tracing back from the "PredictConfig" from infer.py . Please suggest me the right way to do it if I have gone wrong somewhere.

Thanks,
Sid

**Comment by vqdang** [comment] 2019-10-14 01:06
@siddharthamantrala Sorry, I was quite busy so I didn't know you post. And, for what it is worth, you should read this entire thread because we actually guided someone else to run the code here. And to answer your question, its in here also
https://github.com/vqdang/hover_net/issues/12#issuecomment-535971268
Please follow as close as possible to the all the README.

**Comment by simongraham** [comment] 2019-10-14 18:02
@siddharthamantrala please update us with your progress and if we helped you solve the problem. As @vqdang mentioned, it looks like there is a mismatch with the Tensorpack version - please refer to `requirements.txt`

**Comment by siddharthamantrala** [comment] 2019-10-15 11:03
Thanks for the help @vqdang and @simongraham, I am trying to setup the environment for requirements.txt. The issue is tensorflow 1.12.0 works with CUDA 9.0, and CUDA 9.0 can only be installed in Ubunut 16.04. And in Ubuntu 16.04 I am not able to install python 3.6. 

With the below environment I was getting the AssertionError of tf.test.is_gpu_available().
python 3.5.2
tensorFlow 1.12
tensorpack 0.9.0.1
opencv 3.2
skimage
matplotlib
numpy 

Please suggest.

Thanks,
Sid

**Comment by vqdang** [comment] 2019-10-15 16:46
@siddharthamantrala could you tell me how did you install the cuda? A quick search on google suggests that this error is due to mismatching between CUDA, cudnn, and the installed tensorflow. Check this for the matching.
https://www.tensorflow.org/install/source#linux

python 3.5 is ok actually.

**Comment by siddharthamantrala** [comment] 2019-10-15 18:46
@vqdang , I installed cuda using docker, I happen figure out that issue later. Thanks for the help.
